# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-08-31 08:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QiuShiArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='匿名', max_length=200, verbose_name='作者')),
                ('url', models.URLField(verbose_name='文章连接')),
                ('content', models.TextField(default='u无', verbose_name='')),
                ('image', models.ImageField(default='full/default.jpg', upload_to='', verbose_name='图片')),
                ('crawl_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='抓取时间')),
            ],
            options={
                'verbose_name': '糗事百科文章',
                'verbose_name_plural': '糗事百科文章',
            },
        ),
    ]
