# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-09-06 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZhiHuQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zhihu_id', models.CharField(max_length=50, verbose_name='知乎ID')),
                ('topics', models.CharField(max_length=200, verbose_name='主题标签')),
                ('url', models.CharField(max_length=200, verbose_name='链接')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('answer_num', models.IntegerField(verbose_name='回答个数')),
                ('comments_num', models.IntegerField(verbose_name='评论个数')),
                ('watch_user_num', models.IntegerField(verbose_name='关注人数')),
                ('click_num', models.IntegerField(verbose_name='浏览人数')),
                ('crawl_time', models.DateTimeField(verbose_name='抓取时间')),
            ],
            options={
                'verbose_name': '知乎问题',
                'verbose_name_plural': '知乎问题',
            },
        ),
    ]
