# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-08-31 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZhiLianJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('url', models.URLField(verbose_name='链接')),
                ('salary_max', models.IntegerField(verbose_name='最高薪资')),
                ('salary_min', models.IntegerField(verbose_name='最低薪资')),
                ('work_years', models.IntegerField(verbose_name='工作年限')),
                ('work_city', models.CharField(max_length=20, verbose_name='工作城市')),
                ('degree_need', models.CharField(max_length=20, verbose_name='学历')),
                ('job_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='工作类型')),
                ('publish_time', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('job_advantage', models.CharField(blank=True, max_length=200, null=True, verbose_name='职位诱惑')),
                ('job_desc', models.TextField(verbose_name='职位描述')),
                ('job_addr', models.CharField(max_length=150, verbose_name='工作地址')),
                ('company_name', models.CharField(max_length=200, verbose_name='公司名称')),
                ('crawl_time', models.DateTimeField(verbose_name='抓取时间')),
                ('user_nums', models.IntegerField(verbose_name='需求人数')),
            ],
            options={
                'verbose_name_plural': '智联职位信息',
                'verbose_name': '智联职位信息',
            },
        ),
    ]
